### ISSUE TITLE
Feature: CoffeeScript concatenation

### ISSUE THREAD

**Issue by jacob1237** [laravel/elixir#129]
Hello!

This is a feature request.
Please add an ability to concatenate CoffeeScript during the compile process, because for now we need to fully re-implement ingredients/coffee.js file to achieve that.
I think it is very strange behaviour =)

Thank you!

**Comment by JeffreyWay** [comment]
Can you compile your CoffeeScript, and then just call the `scripts()` method on whatever should then be concatenated?

**Comment by jacob1237** [comment]
I've thought about it, but haven't found a way (with Elixir) to clean temporary files before (or after) compilation process.

So, anyway, we need to install additional dependencies to do that (gulp-clean or laravel-elixir-clean).
IMHO it breaks simplicity of Laravel way, because 'clean' functionality is not included in standard package.

And what if I want to do all this process (compile CoffeeScript + scripts() + clean()) by the 'gulp watch'?

**Comment by cve** [comment]
We using this https://medium.com/@morrislaptop/laravel-elixir-for-dev-tasks-or-build-tasks-d5be30f16569 excelent approach and this concatenation feature breaks it... :/ When we run gulp, the coffe task always returns one file 'app.js' We don't want concatenation, because in large application, when olny one file has changed, then gulp coffee must reconcatenate all of the files - it takes to long for us, so for development we prefer to reprocess each files individually which is fast and simple for debuging...

I don't know how can I checkout specific version of Elixir without this breaking feature, cause npm update pulls it for us... :(

This is our gulpfile.js:
````
var elixir = require('laravel-elixir');
require('laravel-elixir-useref');

var bower_path = 'public/bower_components/';

var fonts = {
 bootstrap: bower_path + 'bootstrap/fonts/**'
};

elixir(function (mix) {
 mix
     .less(null, 'public/css/build')
     .copy(fonts.bootstrap, 'public/fonts')
     .coffee(null, 'public/js/build')
     .useref({
      src: false
     })
     .version(['public/js/front.js', 'public/css/front.css', 'public/js/admin.js'])
 ;
});

**Comment by JeffreyWay** [comment]
This is done now.
