### ISSUE TITLE
this.registerWatcher not defined

### ISSUE THREAD

**Issue by deshiknaves** [laravel/elixir#225]
Recently updated laravel elixir and it no longer seems to have registerWatcher

this.registerWatcher("sasscmq", './resources/assets/sass/**/*.scss');
         ^
TypeError: undefined is not a function

**Comment by unitedworx** [comment]
i have a problem with registerWatcher as well after updating elixir!

the below code i had in my gulp file does not seem to work and can't figure out how to update this to work!
elixir.config.registerWatcher("default", "views/**");

p.s i used this since i have my js and css files under /views/ and not /resources/

**Comment by tommhuth** [comment]
Have the same problem. 

See also https://github.com/laravel/framework/issues/9771

**Comment by JeffreyWay** [comment]
Read the release notes. Extensions are a bit different now.

https://github.com/laravel/elixir/releases

If you need the old way, stick with ^2.0.0 of Elixir.

**Comment by deshiknaves** [comment]
That's awesome. My bad, I thought I looked at the docs on Laravel.com as I thought it might have changed. I must have looked at older docs.

**Comment by nezaboravi** [comment]
copy/pasted as its on laravel 5.3 elixir and in github, and keep getting this error: Task 'speak' is not in your gulpfile
