### ISSUE TITLE
Elixir phpunit does not notify for passed tests

### ISSUE THREAD

**Issue by emmanuellozoya** [laravel/elixir#307]
I am building a project using Laravel 5.
I use Gulp and Elixir, and like the notification dialog that tells me the status of my tests.

Now, it is not appearing the Green Test Status dialog (the Red Test Status dialogs is working fine).

I am figuring out why, and I discover that if I remove a test file it works, but if I add one more test it does not work.

For example, If add the following test file, and the Green Test Status dialog does not appear:
```
<?php

class FooTest extends TestCase
{
    public function testFoo()
    {   
      $this->assertTrue(true);
    }   
}
```
Note: Also, the log `"gulp-notify: [PHPUnit Passed] All tests passed!"` does not appear in the console.

I was doing some console.log's inside the file `node_modules/laravel-elixir/Notification.js`, but I could not find why this is happening.

I still cannot fix this problem, so I write my own gulp task for phpunit, but I would like to solve this issue.

OS: Ubuntu 14.04 LTS 64-bit
node: v4.1.2

Link:
http://stackoverflow.com/questions/33060276/elixir-phpunit-does-not-notify-for-passed-tests

**Comment by emmanuellozoya** [comment]
I discover one thing.
If I comment or set onLast to false I receive many passed notifications.

```
 55 /**
 56  * Display a notification for passed tests.
 57  *
 58  * @param {string} framework
 59  */
 60 n.forPassedTests = function(framework) {
 61     return notify({
 62         title: 'Green!',
 63         message: 'Your ' + framework + ' tests passed!',
 64         icon: __dirname + '/icons/pass.png',
 65         //onLast: true
 66     });
 67 };
```

Console output:
```
Time: 2.15 seconds, Memory: 44.75Mb

OK (58 tests, 98 assertions)
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
[18:22:05] gulp-notify: [Green!] Your phpUnit tests passed!
```

**Comment by emmanuellozoya** [comment]
I do not know if this is the right solution, but it works for me.
I just commented the 13 line, and added the 14 line.

laravel-elixir/tasks/shared/Tests.js
```
  1 var gulp = require('gulp');
  2 var Elixir = require('../../index');
  3 
  4 var notify = new Elixir.Notification();
  5 
  6 
  7 module.exports = function(options) {
  8     new Elixir.Task(options.name, function() {
  9         this.log(options.src);
 10 
 11         return (
 12             gulp
 13             //.src(options.src)//THIS LINE WAS COMMENTED
 14             .src("phpunit.xml")//THIS LINE WAS ADDED
 15             .pipe(options.plugin('', options.pluginOptions))
 16             .on('error', function(e) {
 17                 notify.forFailedTests(e, options.name);
 18 
 19                 this.emit('end');
 20             })
 21             .pipe(notify.forPassedTests(options.name))
 22         );
 23     })
 24     .watch(options.src, 'tdd')
 25     .watch(Elixir.config.appPath + '/**/*.php', 'tdd')
 26     .watch('./resources/views/**/*.php', 'tdd')
 27 };
```

**Comment by laracasts** [comment]
What does your Gulpfile look like?

I just did a fresh install, added `mix.phpUnit(), and the green success notification popped right up.

**Comment by emmanuellozoya** [comment]
This is my Gulpfile:

```
  1 var elixir = require('laravel-elixir');
  2 require('laravel-elixir-livereload');
  3 
  4 /*
  5  |--------------------------------------------------------------------------
  6  | Elixir Asset Management
  7  |--------------------------------------------------------------------------
  8  |
  9  | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 10  | for your Laravel application. By default, we are compiling the Sass
 11  | file for our application, as well as publishing vendor resources.
 12  |
 13  */
 14 
 15 elixir(function(mix) {
 16     mix.sass('app.scss');
 17     mix.copy('node_modules/bootstrap-sass/assets/fonts/bootstrap', 'public/build/fonts/bootstrap');
 18     mix.copy('bower_components/font-awesome/fonts', 'public/build/fonts');
 19     mix.phpUnit();
 20     //Scripts
 21     mix.copy('node_modules/bootstrap-sass/assets/javascripts', 'resources/assets/js/vendor/bootstrap');
 22     mix.copy('bower_components/jquery/dist', 'resources/assets/js/vendor/jquery');
 23     mix.copy('node_modules/angular', 'resources/assets/js/vendor/angular');
 24     mix.copy('node_modules/angular-ui-bootstrap', 'resources/assets/js/vendor/angular-ui-bootstrap');
 25     mix.copy('node_modules/salvattore/dist', 'public/js/vendor/salvattore');
 26     mix.scripts([
 27       'vendor/jquery/jquery.min.js',
 28       'vendor/bootstrap/bootstrap.min.js',
 29       'vendor/angular/angular.min.js',
 30       'vendor/angular-ui-bootstrap/ui-bootstrap-tpls.min.js',
 31       'elozoya/ecommerce/src/ecommerce.js',
 32       'elozoya/ecommerce/src/stores/stores.js',
 33       'elozoya/ecommerce/src/photos/photos.js',
 34       'elozoya/ecommerce/src/products/products.js',
 35       'app.js'
 36     ]);
 37     mix.version(['public/css/app.css', 'public/js/all.js']);
 38     mix.livereload();
 39 });
```

**Comment by emmanuellozoya** [comment]
Why does elixir not do the following
```
 11         return (
 12             gulp
 13             //.src(options.src)//THIS LINE WAS COMMENTED
 14             .src("phpunit.xml")//THIS LINE WAS ADDED
 15             .pipe(options.plugin('', options.pluginOptions))
 16             .on('error', function(e) {
 17                 notify.forFailedTests(e, options.name);
 18 
 19                 this.emit('end');
 20             })
 21             .pipe(notify.forPassedTests(options.name))
 22         );
```

I read the official gulp-phpunit documentation, and all the examples pass as first argument to gulp.src the value `'phpunit.xml'`.

Links:
https://www.npmjs.com/package/gulp-phpunit
https://github.com/mikeerickson/gulp-phpunit

**Comment by JeffreyWay** [comment]
I still can't reproduce this. I get the green notification for all my projects.

Can anyone else confirm this issue?

**Comment by blitux** [comment]
I can reproduce it on Linux. 

My settings:

```
// Gulpfile.js
var elixir = require('laravel-elixir');

elixir(function(mix) {
    mix.phpUnit('**/*.php');
});
```

*Versions:*

node: 0.12.7
gulp: 3.9.0 installed globally
laravel-elixir: 3.4.2

Installed with npm cache clear and later npm install

*Console Output:*

```bash
▶ gulp tdd        
[19:29:31] Using gulpfile ~/apps/Stats/Gulpfile.js
[19:29:31] Starting 'tdd'...
Watching for tests...
[19:29:36] Finished 'tdd' after 4.71 s
[19:29:39] Starting 'phpUnit'...
Fetching PhpUnit Source Files...
   - **/*.php
[19:29:39] Finished 'phpUnit' after 22 ms
[19:29:39] *** Debug Cmd: ./vendor/bin/phpunit --colors --debug -c phpunit.xml ***
[19:29:39] PHPUnit 4.8.9 by Sebastian Bergmann and contributors.
Time: 170 ms, Memory: 4.75Mb
# Tests results here
OK (5 tests, 5 assertions)
# Note there's no gulp-notify message here...
[19:30:07] Starting 'phpUnit'...
Fetching PhpUnit Source Files...
   - **/*.php
[19:30:07] Finished 'phpUnit' after 11 ms
[19:30:07] *** Debug Cmd: ./vendor/bin/phpunit --colors --debug -c phpunit.xml ***
[19:30:07] PHPUnit 4.8.9 by Sebastian Bergmann and contributors.
Time: 107 ms, Memory: 5.00Mb
# Test results here
FAILURES!
Tests: 6, Assertions: 6, Failures: 1.
[19:30:07] { 
[Error: Command failed: /bin/sh -c ./vendor/bin/phpunit --colors --debug -c phpunit.xml]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c ./vendor/bin/phpunit --colors --debug -c phpunit.xml' }
[19:30:07] gulp-notify: [Red!] Your phpUnit tests failed!
```

**Comment by blitux** [comment]
I'm trying my best to debug the issue although I'm not a node.js person. 

Currently I've tracked down the issue to `gulp-notify`. It seems calling `notify()` directly on [Notification.js:61](https://github.com/laravel/elixir/blob/master/Notification.js#L61) doesn't have any effect. It appears to need a stream to work, and inside `n.forPassedTests()` method it doesn't get it.

I've tried to workaround the issue, but I'm not skilled enough on node. Tried, for example, to require `gulp-notify` on `tasks/shared/Tests.js` and then fire the notification on L20 calling directly to `notify(options)`, and it worked, but only if the option `onLast` was set to false. It showed a lot of notifications, though.

Some alternative solutions require `node-notifier` to show up the notification directly. 

Anyways this should shed some light on the issue.

**Comment by parsnick** [comment]
Not a node person either, but bear with me...

I *think* this, and a lot of other issues with gulp plugins not completing, can be traced back to the highWaterMark option in node streams. 

The stream can only hold so much data and when it's full, anything else coming through the input pipe won't get processed until we make some room for it. So we need to add an output pipe (in the water analogy) to drain the stream and "pull" more data through. 

gulp-notify uses `through.obj()`, which is documented as a shortcut for `through({ objectMode: true }, ...)` but crucially *also sets highWaterMark to 16*. If our stream ends here, only the first 16 files get processed. Combined with the onLast option, it never reaches the last file so the notification never appears.

**So, when does the stream have more than 16 files?**

Whatever you pass to `mix.phpUnit()` gets used as the `gulp.src()` *and gets a watcher*. It defaults to `tests/**/*Test.php`. Watchers for the app and views directories are set separately.

On a Laravel project, everything appears to work fine and you'll only encounter the missing notification if you have more than 16 test files.

But if you don't have a Laravel-like directory structure, the additional watchers for the app and view directories don't do anything. You tend to end up giving `mix.phpUnit()` a pattern that matches *all* of your source code - which obviously hits the 16 file limit far more often, explaining why the issue seems far more prevalent in non-Laravel projects.

(Also, since the fail notification is handled differently, that always works.)

**Enough rambling, what's the solution?**

Lots of options:

1. I've submitted a [pull request to gulp-notify](https://github.com/mikaelbr/gulp-notify/pull/101) but not entirely sure about my "solution" to be honest. 

2. Workaround by adding to something to consume the stream after the call to `gulp-notify`. Appending `.resume()` to the pipeline at [tasks/shared/Tests.js:19](https://github.com/laravel/elixir/blob/master/tasks/shared/Tests.js#L19) sorted the problem on my machine.

3. But..., @emmanuellozoya's suggestion sounds like the best option. Both `gulp-phpunit` and `gulp-phpspec` explicitly do nothing for all but the first file, and `gulp-notify` with onLast does nothing except on the last file. All three plugins ignore the actual content of the stream, so setting the gulp.src to a single file (phpunit.xml or phpspec.yml) shouldn't cause any problems. Should also be a bit faster without a load of unnecessary files being passed through the pipeline.

Happy to submit PR for this if @JeffreyWay is okay with proposed solution. Apologies for lengthy reply.

**Comment by JeffreyWay** [comment]
I've removed both gulp-phpunit and gulp-phpspec. So now (once I tag it) Elixir just pipes out to a shell script.

**Comment by emmanuellozoya** [comment]
Thank you
