### ISSUE TITLE
Is it possible to install Elixir without all those dependencies?

### ISSUE THREAD

**Issue by igorsantos07** [laravel/elixir#334]
I'm using Elixir in a project that needs Coffee, Less, Autoprefixer and Versioning. However, I did notice that by default Elixir comes bundled with a lot of plugins we won't be using, such as Sass, Browserify, Vue, PHPUnit, and so on.

Would be great to be able to specify what plugins we wanted, thus speeding up the install procedure - and potentially saving disk space and network (important in slow connections.. think about installing the project over a slow wifi).

**Comment by FWSimon** [comment]
Good idea +1

**Comment by igorsantos07** [comment]
One more good use case for this: deployment.
Headless servers (all decent PHP/JS servers?) won't work with `gulp-notify`, issuing several false warnings and poluting output when your deployment procedure runs `gulp --production`:

```
remote:        [15:30:16] Finished 'default' after 366 ms
remote:        [15:30:18] gulp-notify: [Laravel Elixir] Less Compiled!
remote:        [15:30:18] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
remote:        Message:
remote:            not found: notify-send
```

**Comment by jp7carlos** [comment]
+1
It will probably be hard to decouple Elixir from all these dependencies, but if you manage to move them to "optional dependencies" it would be an important improvement IMO.

While on your dev machine 300 MB of dependencies and 5 minutes of "npm install" is tolerable, it becomes really slow when you run "npm install" during deploy, or when you want to use automated builds to create Docker images from a Git repository.

I tried to remove all the Elixir dependencies I don't use and the size of node_modules when down to 100MB, but i had to manually edit Elixir files and editing vendor code is not a good idea.

It would also make easier for Elixir to add support for other frameworks without growing too big. Since the extra stuff would be optional, size wouldn't matter.

**Comment by jp7rafael** [comment]
Great idea +1

**Comment by JeffreyWay** [comment]
I think it would be a cool idea. I'm just not sure how we'd go about doing that. PRs welcomed if you have any ideas.

**Comment by igorsantos07** [comment]
Sorry, but it makes sense to close an issue that seems cool and important and that was not actually closed, just because we currently do not know how to do it? If you leave it open other people can take a look and try to tackle it later.

**Comment by JeffreyWay** [comment]
I don't see any way to do it with Elixir, without forking it.

**Comment by mikeerickson** [comment]
Sounds like it would be easier just to create your own gulp tasks as needed.  If you don't need all that Elixir offers, just go for your own gulp tasks.

**Comment by lazabogdan** [comment]
Hey @JeffreyWay, 

I was just looking into this and about to do a fork myself. 

How about:

1. Extract the main Elixir module and the core API into a dedicated package (so stuff like Config, Task, GulpPaths, Logger, Notification, the default task etc) and maybe call this something more generic like gulp-elixir
2. Make the tasks pluggable like laravel-elixir-webpack, each with it's own package and dependencies
3. Update laravel-elixir to simply load the tasks it needs for it's assumed default usage with Laravel

This way users of laravel-elixir will be unaffected, getting the same tasks and their dependencies loaded by default, and for those who want to use elixir outside of laravel, they can just install gulp-elixir with minimal dependencies and simply load/plug-in the tasks they need for their project.

If you're willing, I would much prefer to work on this and help with whatever you think it's necessary rather than starting to separate this on my own and then having to manually track down and implement eventual updates you'll make here. Makes sense?

Let me know what you think.

**Comment by devboxr** [comment]
Any news on this? It would be a much better product if this would be possible.
