### ISSUE TITLE
Build vendor.js when using browserify.externals config

### ISSUE THREAD

**Issue by thoughts1053** [laravel/elixir#355]
How would you build the vendor.js or main.js file when trying to use the externals config for browserify?

How do you specify for that file to require different libraries so other files can find it?

**Comment by DarkaOnLine** [comment]
I solved problem like this:

Created gulp-global.js file, where i put all css and js libraries which are used in all views:
```js
elixir(function(mix) {
    mix.sass('global.scss', public_css + '/global.css')
        .browserify('global.js');
});
```
runing gulp with command `gulp --gulpfile gulp-global.js`

And in the mail gulpfile.js I have

```js
elixir.config.js.browserify.externals.push('jquery');
elixir(function(mix) {
	mix.browserify('views/records.js', public_js + '/views/records.min.js');
	mix.browserify('views/tasks.js', public_js + '/views/tasks.min.js');
	.......
});
```

**Comment by thoughts1053** [comment]
@DarkaOnLine, I'd rather not have two gulp files. I might end up making my own gulp task to take care of the main/global js.

**Comment by FridayMarch26th** [comment]
For the last day or two I've been in the same boat as @thoughts1053.

So a vendor bundle, and an application bundle.

The vendor bundle should be created with [external requires](https://www.npmjs.com/package/browserify#external-requires) so the modules inside it can be referenced from other script tags (our application bundle).

We create the two bundles: vendor.js, and then app.js with the vendor modules specified as external. However, with Elixir external modules are declared globally in its Browserify config, rather than in a specific bundle's options.

This was actually flagged by @thoughts1053 on the pull request that added external modules to the Browserify config (https://github.com/laravel/elixir/pull/305). Good to note, I think, as declaring external modules across the board isn't hugely useful.

In the end I tweaked a small section of Elixir's Browserify task, so that each bundle can specify its own external modules rather than relying on the broad config - exactly as @thoughts1053 pointed out in the recent pull request. Everything's now bundling correctly.

That's hopefully of some use.

Cheers,

**Comment by thoughts1053** [comment]
@FridayMarch26th, did you submit a pull request or just make the changes on your local install?

**Comment by FridayMarch26th** [comment]
Just local, but the thought of submitting something made me reconsider how I'd achieved the vendor/app split.

TBH, it involved hijacking a bundle's options object (intended for Browserify) to pass data to Elixir's Browserify task. I was initially pleased to get *anything* working, but a second read through what I'd done revealed that it just wasn't good.

So a better way then, and in particular an answer to why the following doesn't work:

```
mix.browserify('vendor.js', null, null, {require: ['jquery'])
   .browserify('app.js', null, null, {external: ['jquery']);
```

Well, there's actually nothing in Browserify to intercept { external: [] } as there is for { require: [] }. To me it feels to have one 'half' of the external requires puzzle without the other, and it's currently where Elixir steps in to fill the gap.

So a pull request? Probably, but it would be to add { external: [] } handling to Browserify (on the surface this is very easy, but it's worth a thought or two*).

*A disclaimer: I'm brand new to Browserify. In fact I only started getting to grips with it because it was on tap with Elixir. Therefore, my opinion of what is right and wrong in this space is still moving around significantly.

**Comment by thoughts1053** [comment]
@FridayMarch26th, I had the exact same thought process when looking at this problem initially. I actually made an issue on the browserify repo a month ago: https://github.com/substack/node-browserify/issues/1430.

**Comment by FridayMarch26th** [comment]
Ha! I was looking for that. :)

Good to know I'm not the only one.

**Comment by FridayMarch26th** [comment]
One more on this, a small discussion of opts.require. https://github.com/substack/node-browserify/issues/1220.

Based on that, it's not clear whether opts.external (and presumably opts.ignore, opts.exclude...) should join opts.require, or whether it would be better to adjust Elixir to fit with more common Browserify usage (which strikes me as a bit of a shift).

**Comment by grmlin** [comment]
So I have to separate my JS into bundles and I don't see a way how to do it at the moment, using the global `elixir.config.js.browserify.externals` array. 

Are there any other options than the usage of another gulpfile or a custom browserify task? (I can't see any looking into the sources)

Thanks!
