### ISSUE TITLE
mix.version creates new files instead of overriding and renaming the old ones

### ISSUE THREAD

**Issue by PhillippOhlandt** [laravel/elixir#393]
That's very annoying when you add the compiled files to git (I have reasons). Because when you regenerate them, you have to add the new files to git. I often forget that because I just hit the "Commit Directory" option in phpstorm.

**Comment by PhillippOhlandt** [comment]
ping @JeffreyWay

**Comment by parsnick** [comment]
Perhaps I'm misunderstanding but if you're forgetting a step in your own workflow, how is that a Elixir issue?

**Comment by PhillippOhlandt** [comment]
Because it creates new files in the background. Why should I add all files every time before I commit? I don't created new files myself so no need to click "Add files".

**Comment by parsnick** [comment]
> Because it creates new files in the background.

But that's exactly what [it says it does](https://laravel.com/docs/5.1/elixir#versioning-and-cache-busting) (emphasis added):

> The version method [...] will **append a unique hash to the filename**, allowing for cache-busting. For example, the generated file name will look something like: all-16d570a7.css

What are you expecting to happen?

**Comment by PhillippOhlandt** [comment]
I expect it just overrides and renames the old one.

**Comment by thecrypticace** [comment]
Git does not track renamed files. It uses diff heuristics to determine if files are sufficiently similar to be considered a rename. Git will pick up a the combination of a new file and deleted file as a rename with changes as long as they are similar enough. If the files are not within the the similarity threshold, Git will not track the change as a renamed file. Renaming files at the filesystem level does nothing for Git as it does not track changes at that level.

This Stack Overflow answer may also be able to provide some more insight: http://stackoverflow.com/a/12785491/636855

FWIW, I use Elixir's versioning and as long as the files are similar enough Git will note that it appears to be a renamed file. But, again, this is due to the heuristics used by Git to track changes between files.

**Comment by PhillippOhlandt** [comment]
Thanks for the explanation how git detects renamed files. Wasn't aware of it.

For the "add files" thing: I usually use phpstorm and use it for git interactions as well. There I don't have to add files before commit, only if there are new files.

**Comment by thecrypticace** [comment]
Sure thing, glad I could help. Yea, I think PHPStorm automatically stages all changes for files it knows about when you go to commit. It is somewhat misleading to the nature of how Git actually works but it can be handy.
