### ISSUE TITLE
npm install laravel-elixir --save-dev "stream-browserify@* but none was installed"

### ISSUE THREAD

**Issue by FDiskas** [laravel/elixir#610]
```
  +-- underscore@1.8.3
  `-- vinyl-map@1.0.1
    +-- bl@0.7.0
    | `-- readable-stream@1.0.34
    +-- new-from@0.0.3
    | `-- readable-stream@1.1.14
    +-- UNMET PEER DEPENDENCY stream-browserify@*
    `-- through2@0.4.2
      `-- xtend@2.1.2
        `-- object-keys@0.4.0
npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
```
npm -v ```3.10.3```
node -v ```v6.3.1```
Windows 10

**Comment by laracasts** [comment]
I don't think you need to install anything else. Elixir gives you everything you need.

**Comment by FDiskas** [comment]
Yes I know. But I got this error just by executing this command
```npm install laravel-elixir --save-dev```

**Comment by randohinn** [comment]
Not an error. @laracasts is completely right.

@FDiskas npm not installing peer dependencies is a feature since npm 3, not a bug, and is completely unrelated to laravel or elixir. This does no harm to your environment. It's only a Warning - therefore the `WARN` it prints out :smile:  See the [npm changelog](https://github.com/npm/npm/blob/master/CHANGELOG.md#peerdependencies) for details.
