### ISSUE TITLE
mix.webpack is not creating files when called by 'gulp watch'

### ISSUE THREAD

**Issue by janokary** [laravel/elixir#624]
In my gulpfile, I have multiple calls to mix.webpack() 
(they called Browserify before upgrading to Elixir 6.0) that worked fine in the prior version.

I've found that if I delete all but one of the calls to webpack(), it watches that file without any issues. However when you start adding multiple calls, it gets a little crazy and it is not even create the files in the first place.
This is the output I get when calling gulp watch with three separate calls to mix.webpack():

```
webpack is watching for changes
webpack is watching for changes
webpack is watching for changes
webpack is watching for changes
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: EINVAL: invalid argument, write
    at Error (native)
```

**Comment by danielsdeboer** [comment]
I have the same problem. I need to make multiple bundles so concatenating the files isn't what I want.

I managed to work around this issue by using yargs: [https://www.npmjs.com/package/yargs](url) 

It's not super ideal but since I'm generally not working on code from more than one bundle at once I wrap my elixir calls in an `if` block like so:

```
if (argv.whatever) { 
    elixir(function(mix) { 
        // etc 
    }); 
}
```

Then I can run `gulp watch --whatever` to watch only that one stream.

A caveat is that versioning can't be inside an `if` block or your `rev-manifest.json` file will only contain a reference to that particular bundle.

**Comment by janokary** [comment]
Ok the discussion about this issue continues here [#598](https://github.com/laravel/elixir/issues/598#issuecomment-243967019) (though the original post is not exactly about this issue).
