### ISSUE TITLE
Elixir is not exiting with non-zero exit code on failure

### ISSUE THREAD

**Issue by martinssipenko** [laravel/elixir#71]
In cases where some tasks fail, the exit code remains 0.

```
[09:06:35] Starting 'less'...
[09:06:36] gulp-notify: [Laravel Elixir] Error: Unrecognised input in file /path/test.less line no. 1
[09:06:36] Finished 'less' after 1.01 s
```

```
$ echo $?
0
```

As a consequence of this CI servers that are doing asset compilation do not fail the build on failures.

**Comment by JeffreyWay** [comment]
I think this is a Gulp thing?? Not sure. If you know how to fix, submit a PR.

**Comment by iakio** [comment]
That is because elixir catches errors.
If elixir doesn't catch errors, it will exit with none 0 exit code. But, `gulp watch` will stop if an error happened.

I think, to solve this:
- change error handling behavior by context (watching or not). 
- add new option like this:
http://www.artandlogic.com/blog/2014/05/error-handling-in-gulp/

**Comment by jorisnoo** [comment]
One way to achieve this it to overwrite the the `Elixir.Notification.prototype.error` function and to decide there, how the error should be handled.
