### ISSUE TITLE
A Browserify Task in Core

### ISSUE THREAD

**Issue by JeffreyWay** [laravel/elixir#84]
A tough thing about Elixir is that everyone wants every possible tool to be part of core. Hopefully, it's easy to see that this simply doesn't scale. That's why you can either mix in your own tasks:

```js
gulp.task('foo', function() {
    return gulp.src('...');
};

// ...

elixir(function(mix) {
    mix.task('foo');
});
```

Or even create extensions for others to use. 

However, I personally would like to see a `browserify` task out of the box. If we include it by default, we can push a best practice for Laravel users, and even allow them to use ES6 (if they wish) without needing to spend hours researching Gulp transformations, bundling, etc.

```js
mix.browserify('react/index.jsx');
```

Thoughts? Yay, nay? Here's how it could work (quickie video):

https://www.dropbox.com/s/qakznkmlp1jklmw/ex.mp4?dl=0

**Comment by nathggns** [comment]
You use a react example (jsx) but a lot of people in the React community favour webpack. Why should Browiserify be included over Webpack. Can we include both (SASS/LESS)?

**Comment by nathggns** [comment]
Browserify*

**Comment by tommymarshall** [comment]
:+1: Great as a default IMO. Winds are shifting towards Webpack, but it's overkill (more confugration, need separate dev server running for hot module replacement, and it's for specific JS-heavy apps). Browserify is great for what 95% of what we're doing, and the remaining 5% already have their own FED toolkit anyways.

@nathggns Elixir already can compile both SASS and LESS.

**Comment by ayatojhans** [comment]
I love this idea. Even if you don't plan to use React, Browserify is such a neat tool to require your dependencies and bundle them all together.

**Comment by nathggns** [comment]
I know it can already compile SASS and LES. I used that as an example of why including both could be a good idea.

**Comment by JeffreyWay** [comment]
Yeah - there's nothing that says you need to use React. That was just an example. You can use general JS.

**Comment by tymondesigns** [comment]
@JeffreyWay Since you mentioned ES6... thoughts on introducing [babeljs](https://babeljs.io/) as part of core ?

**Comment by JeffreyWay** [comment]
@tymondesigns If we added a browserify() mixin, I'd include a call the `babelify`.

**Comment by tymondesigns** [comment]
or that.. nice one ;)

**Comment by nathggns** [comment]
While I'm completely for this, I still think it's worth including both Browserify and Webpack (for the same reason we include both SASS and LESS).

**Comment by JeffreyWay** [comment]
And then you're back to that discussion, where people want everything included...

**Comment by tymondesigns** [comment]
I think browserify is a good candidate for the core, since as you say, it will provide some good practices out of the box, and save time for Laravel users that may not be as savvy in this area.

I can see the logic behind "if we use SASS & LESS then why not Browserify and Webpack", 
but then you could say... why not include Typescript, Livescript and Dart since we offer Coffeescript? etc.. 

The line has to be drawn somewhere..

**Comment by loganhenson** [comment]
I use and love elixer because it creates that happy path everyone is looking for. While it doesn't include everything, by default its goal is to present a set of conventions and solutions that allow people to "fall into the pit of success" in a supported way. 

I would love to delete my boilerplates/opinions in the front end space for the stability/consistency of an officially supported way to walk down the "future of JavaScript" road. I trust Jeff to make an educated/informed decision and pick a good solution. Can't wait!

**Comment by EdRands** [comment]
I've looked into Browserify before, and struggled. I'd love it if you could add it to Elixir to make it Laravel simplified for me.

**Comment by JeffreyWay** [comment]
Thanks, all. Going to add this.
